feat: Import Assets Text Style Catalog
FightPandemics/FightPandemics-iOS-SwiftUI pull request #10
Opened 2020-09-10 18:01 UTC by lucianoschillagi

2020-09-10 18:05 UTC, stavares843 approved these changes

2020-09-12 15:04 UTC, Power186 reviewed
Was it intentional to change the deployment target from 13.6 to 13.3?

Was it intentional to change the development team?

2020-09-12 15:17 UTC, Power186 approved these changes
Looks good, but will checkout deployment target change and dev team change

2020-09-12 15:28 UTC, Power186 requested changes

2020-09-12 15:28 UTC, Power186 commented on FightPandemics.xcodeproj/project.pbxproj
> -				IPHONEOS_DEPLOYMENT_TARGET = 13.6;
Should not be changed, merge conflict

2020-09-12 15:28 UTC, Power186 commented on FightPandemics.xcodeproj/project.pbxproj
> -				IPHONEOS_DEPLOYMENT_TARGET = 13.6;
Merge conflict

2020-09-12 15:28 UTC, Power186 commented on FightPandemics.xcodeproj/project.pbxproj
> -				DEVELOPMENT_TEAM = Q7KJCMM3NN;
Merge conflict

2020-09-12 17:12 UTC, lucianoschillagi commented
Ok, thanks. I will do this changes.

2020-09-12 19:03 UTC, lucianoschillagi commented
I am using **Xcode 11.4** and my max iOS Development target is **13.4.**
Suggestions?

2020-09-13 03:40 UTC, Power186 commented
> I am using **Xcode 11.4** and my max iOS Development target is **13.4.**
> Suggestions?

Xcode is updated with the updates from Catalina.  My suggestion for now would be to update to the latest Catalina.  Another option, would be downloading the repo from .zip again, opening and making the the import asset changes without touching the deployment target or version..

I'll look more into it today for workarounds other than these two options.  Please let me know if either worked.

2020-09-13 15:47 UTC, closed without merging