Ben/in app registration login ui
FightPandemics/FightPandemics-iOS-SwiftUI pull request #47
Opened 2020-11-12 15:22 UTC by BenRettig2015

Views for the In-App Registration + Log-in
 https://youtu.be/Twk2gD77Y6s

2020-11-14 12:59 UTC, Power186 commented on FightPandemics/ContentView.swift
> +        .titleTextAttributes = [.font: UIFont(name: "Verdana", size: 16)!]   }
.font.. UIFont... not SwiftUI

2020-11-14 13:02 UTC, Power186 commented on FightPandemics/ViewTest.swift
> +        UINavigationBar.appearance().titleTextAttributes = [.font: UIFont(name: "Verdana", size: 16)!]
You can edit the navigation bar with modifiers in SwiftUI, not this archaic UIKit thing going on here, it's confusing seeing it mixed with SwiftUI

2020-11-14 13:12 UTC, Power186 requested changes
In Sign Up / Sign Up Form View, the logic and methods for authenticating a user should be encapsulated away from the view.  So all of those methods need to be put into a class, then add ObservableObject, then make instance in the SignUp/SignIn View with an @StateObject listener for that class, then use that State Object with the methods to show the right views.. This is MVVM pattern.  None of the code submitted here is MVVM.  I would be happy to explain or show further how to clean this code up if you like?  Or what do you think of this?

Other than that, nice work!

2020-11-23 20:17 UTC, closed without merging

2020-12-10 06:04 UTC, BenRettig2015 reviewed
T